export const FETCH_SUCCESS_POST="FETCH_SUCCESS_POST";
export const FETCH_ERROR_POST="FETCH_ERROR_POST";
export const ADD_NEW_POSTS_SUCCESS="ADD_NEW_POSTS_SUCCESS";
export const ADD_NEW_POSTS_ERROR="ADD_NEW_POSTS_ERROR";

